# Generated by Django 3.2.6 on 2021-12-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTimeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Gynecology', 'Gynecology'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='Cardiologist', max_length=50)),
                ('start_date', models.DateField(default=1)),
                ('end_date', models.DateField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_time_slots',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hospital.doctortimeslots'),
            preserve_default=False,
        ),
    ]
