# Generated by Django 3.2.6 on 2022-01-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fridays',
            field=models.CharField(choices=[('Friday Morning', 'Friday Morning'), ('Friday AfterNoon', 'Friday AfterNoon'), ('Friday Everning', 'Friday Everning'), ('Friday Night', 'Friday Night'), ('Friday Unavailable', 'Friday Unavailable')], default='Friday Unavailable', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='mondays',
            field=models.CharField(choices=[('Monday Morning', 'Monday Morning'), ('Monday AfterNoon', 'Monday AfterNoon'), ('Monday Everning', 'Monday Everning'), ('Monday Night', 'Monday Night'), ('Monday Unavailable', 'Monday Unavailable')], default='Monday Unavailable', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='saturdays',
            field=models.CharField(choices=[('Saturday Morning', 'Saturday Morning'), ('Saturday AfterNoon', 'Saturday AfterNoon'), ('Saturday Everning', 'Saturday Everning'), ('Saturday Night', 'Saturday Night'), ('Saturday Unavailable', 'Saturday Unavailable')], default='Saturday Unavailable', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sundays',
            field=models.CharField(choices=[('Sunday Morning', 'Sunday Morning'), ('Sunday AfterNoon', 'Sunday AfterNoon'), ('Sunday Everning', 'Sunday Everning'), ('Sunday Night', 'Sunday Night'), ('Sunday Unavailable', 'Sunday Unavailable')], default='Sunday Unavailable', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='thursdays',
            field=models.CharField(choices=[('Thursday Morning', 'Thursday Morning'), ('Thursday AfterNoon', 'Thursday AfterNoon'), ('Thursday Everning', 'Thursday Everning'), ('Thursday Night', 'Thursday Night'), ('Thursday Unavailable', 'Thursday Unavailable')], default='Thursday Unavailable', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tuesdays',
            field=models.CharField(choices=[('Tuesday Morning', 'Tuesday Morning'), ('Tuesday AfterNoon', 'Tuesday AfterNoon'), ('Tuesday Everning', 'Tuesday Everning'), ('Tuesday Night', 'Tuesday Night'), ('Tuesday Unavailable', 'Tuesday Unavailable')], default='Tuesday Unavailable', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='wednesdays',
            field=models.CharField(choices=[('Wednesday Morning', 'Wednesday Morning'), ('Wednesday AfterNoon', 'Wednesday AfterNoon'), ('Wednesday Everning', 'Wednesday Everning'), ('Wednesday Night', 'Wednesday Night'), ('Wednesday Unavailable', 'Wednesday Unavailable')], default='Wednesday Unavailable', max_length=50),
        ),
    ]
