# Generated by Django 3.2.6 on 2022-01-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20220101_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fridays',
            field=models.CharField(choices=[('Friday Morning 6:00am-8:00am', 'Friday Morning 6:00am-8:00am'), ('Friday Morning 8:00am-10:00am', 'Friday Morning 8:00am-10:00am'), ('Friday Morning 10:00am-11:59am', 'Friday Morning 10:00am-11:59am'), ('Friday Morning 6:00am-11:59am', 'Friday Morning 6:00am-11:59am'), ('Friday AfterNoon 2:00pm-4:00pm', 'Friday AfterNoon 2:00pm-4:00pm'), ('Friday Everning 5:00pm-7:00pm', 'Friday Everning 5:00pm-7:00pm'), ('Friday Night 8:00pm-10:00pm', 'Friday Night 8:00pm-10:00pm'), ('Friday 10:00pm-6:00am', 'Friday 10:00pm-6:00am'), ('Friday Available', 'Friday Available'), ('Friday Unavailable', 'Friday Unavailable')], default='Friday Unavailable', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mondays',
            field=models.CharField(choices=[('Monday Morning 6:00am-8:00am', 'Monday Morning 6:00am-8:00am'), ('Monday Morning 8:00am-10:00am', 'Monday Morning 8:00am-10:00am'), ('Monday Morning 10:00am-11:59am', 'Monday Morning 10:00am-11:59am'), ('Monday Morning 6:00am-11:59am', 'Monday Morning 6:00am-11:59am'), ('Monday AfterNoon 2:00pm-4:00pm', 'Monday AfterNoon 2:00pm-4:00pm'), ('Monday Everning 5:00pm-7:00pm', 'Monday Everning 5:00pm-7:00pm'), ('Monday Night 8:00pm-10:00pm', 'Monday Night 8:00pm-10:00pm'), ('Monday 10:00pm-6:00am', 'Monday 10:00pm-6:00am'), ('Monday Available', 'Monday Available'), ('Monday Unavailable', 'Monday Unavailable')], default='Monday Unavailable', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='saturdays',
            field=models.CharField(choices=[('Saturday Morning 6:00am-8:00am', 'Saturday Morning 6:00am-8:00am'), ('Saturday Morning 8:00am-10:00am', 'Saturday Morning 8:00am-10:00am'), ('Saturday Morning 10:00am-11:59am', 'Saturday Morning 10:00am-11:59am'), ('Saturday Morning 6:00am-11:59am', 'Saturday Morning 6:00am-11:59am'), ('Saturday AfterNoon 2:00pm-4:00pm', 'Saturday AfterNoon 2:00pm-4:00pm'), ('Saturday Everning 5:00pm-7:00pm', 'Saturday Everning 5:00pm-7:00pm'), ('Saturday Night 8:00pm-10:00pm', 'Saturday Night 8:00pm-10:00pm'), ('Saturday 10:00pm-6:00am', 'Saturday 10:00pm-6:00am'), ('Saturday Available', 'Saturday Available'), ('Saturday Unavailable', 'Saturday Unavailable')], default='Saturday Unavailable', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sundays',
            field=models.CharField(choices=[('Sunday Morning 6:00am-8:00am', 'Sunday Morning 6:00am-8:00am'), ('Sunday Morning 8:00am-10:00am', 'Sunday Morning 8:00am-10:00am'), ('Sunday Morning 10:00am-11:59am', 'Sunday Morning 10:00am-11:59am'), ('Sunday Morning 6:00am-11:59am', 'Sunday Morning 10:00am-11:59am'), ('Sunday AfterNoon 2:00pm-4:00pm', 'Sunday AfterNoon 2:00pm-4:00pm'), ('Sunday Everning 5:00pm-7:00pm', 'Sunday Everning 5:00pm-7:00pm'), ('Sunday Night 8:00pm-10:00pm', 'Sunday Night 8:00pm-10:00pm'), ('Sunday 10:00pm-6:00am', 'Sunday 10:00pm-6:00am'), ('Sunday Available', 'Sunday Available'), ('Sunday Unavailable', 'Sunday Unavailable')], default='Sunday Unavailable', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='thursdays',
            field=models.CharField(choices=[('Thursday Morning 6:00am-8:00am', 'Thursday Morning 6:00am-8:00am'), ('Thursday Morning 8:00am-10:00am', 'Thursday Morning8:00am-10:00am'), ('Thursday Morning 10:00am-11:59am', 'Thursday Morning 10:00am-11:59am'), ('Thursday Morning 6:00am-11:59am', 'Thursday Morning 6:00am-11:59am'), ('Thursday AfterNoon 2:00pm-4:00pm', 'Thursday AfterNoon 2:00pm-4:00pm'), ('Thursday Everning 5:00pm-7:00pm', 'Thursday Everning 5:00pm-7:00pm'), ('Thursday Night 8:00pm-10:00pm', 'Thursday Night 8:00pm-10:00pm'), ('Thursday 10:00pm-6:00am', 'Thursday 10:00pm-6:00am'), ('Thursday Available', 'Thursday Available'), ('Thursday Unavailable', 'Thursday Unavailable')], default='Thursday Unavailable', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tuesdays',
            field=models.CharField(choices=[('Tuesday Morning 6:00am-8:00am', 'Tuesday Morning 6:00am-8:00am'), ('Tuesday Morning 8:00am-10:00am', 'Tuesday Morning 8:00am-10:00am'), ('Tuesday Morning 10:00am-11:59am', 'Tuesday Morning 10:00am-11:59am'), ('Tuesday Morning 6:00am-11:59am', 'Tuesday Morning 6:00am-11:59am'), ('Tuesday AfterNoon 2:00pm-4:00pm', 'Tuesday AfterNoon 2:00pm-4:00pm'), ('Tuesday Everning 5:00pm-7:00pm', 'Tuesday Everning 5:00pm-7:00pm'), ('Tuesday Night 8:00pm-10:00pm', 'Tuesday Night 8:00pm-10:00pm'), ('Tuesday 10:00pm-6:00am', 'Tuesday 10:00pm-6:00am'), ('Tuesday Available', 'Tuesday Available'), ('Tuesday Unavailable', 'Tuesday Unavailable')], default='Tuesday Unavailable', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='wednesdays',
            field=models.CharField(choices=[('Wednesday Morning 6:00am-8:00am', 'Wednesday Morning 6:00am-8:00am'), ('Wednesday Morning 8:00am-10:00am', 'Wednesday Morning 8:00am-10:00am'), ('Wednesday Morning 10:00am-11:59am', 'Wednesday Morning 10:00am-11:59am'), ('Wednesday Morning 6:00am-11:59am', 'Wednesday Morning 6:00am-11:59am'), ('Wednesday AfterNoon 2:00pm-4:00pm', 'Wednesday AfterNoon 2:00pm-4:00pm'), ('Wednesday Everning 5:00pm-7:00pm', 'Wednesday Everning 5:00pm-7:00pm'), ('Wednesday Night 8:00pm-10:00pm', 'Wednesday Night 8:00pm-10:00pm'), ('Wednesday 10:00pm-6:00am', 'Wednesday 10:00pm-6:00am'), ('Wednesday Available', 'Wednesday Available'), ('Wednesday Unavailable', 'Wednesday Unavailable')], default='Wednesday Unavailable', max_length=50),
        ),
    ]
