# Generated by Django 3.2.6 on 2022-01-02 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_appointment_appointmentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentDate',
        ),
        migrations.AddField(
            model_name='appointment',
            name='AppointmentDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='AppointmentDate'),
            preserve_default=False,
        ),
    ]
