# Generated by Django 3.2.6 on 2022-01-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20220102_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentDates',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(auto_now=True),
        ),
    ]
